services:
  db:
    image: postgres:16
    container_name: custom_auth_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: custom_auth_db
      POSTGRES_USER: custom_auth_user
      POSTGRES_PASSWORD: custom_auth_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
